/*
  export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
*/
export default {
  login: 'pratik1998-sys',
  id: 64015348,
  node_id: 'MDQ6VXNlcjY0MDE1MzQ4',
  avatar_url: 'https://avatars.githubusercontent.com/u/64015348?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/pratik1998-sys',
  html_url: 'https://github.com/pratik1998-sys',
  followers_url: 'https://api.github.com/users/pratik1998-sys/followers',
  following_url:
    'https://api.github.com/users/pratik1998-sys/following{/other_user}',
  gists_url: 'https://api.github.com/users/pratik1998-sys/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/pratik1998-sys/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/pratik1998-sys/subscriptions',
  organizations_url: 'https://api.github.com/users/pratik1998-sys/orgs',
  repos_url: 'https://api.github.com/users/pratik1998-sys/repos',
  events_url: 'https://api.github.com/users/pratik1998-sys/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/pratik1998-sys/received_events',
  type: 'User',
  site_admin: false,
  name: 'Pratik Singh',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: 'Frontend Developer | Open for work | xTCS Employee',
  twitter_username: 'pratiksingh260',
  public_repos: 7,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2020-04-20T12:02:53Z',
  updated_at: '2023-01-29T14:56:29Z',
}
